root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  include_ext = ["go", "yaml"]
  exclude_dir = ["tmp", "vendor", "storage", "docs"]
  delay = 500

[log]
  time = true

[color]
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
